---
server:
  host: irc.freenode.net
  port: 6667
  nick: rubot-edge
  alt_nick: rubot-edge_
  real_name: rubot
  channels: "#rubot"
  #vhost: 
  quit_message: powered by rubot

function_character: "!"
auth_list: thorncp